# Generated by Django 3.1.5 on 2021-02-20 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210220_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifield',
            name='value_type',
            field=models.CharField(choices=[('0', '整型'), ('1', '浮点型'), ('2', '文本型'), ('3', '日期时间'), ('4', '日期'), ('5', '时间'), ('6', 'JSON'), ('7', '字符串')], max_length=2, verbose_name='值的类型'),
        ),
        migrations.CreateModel(
            name='CIIndexCharValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='索引字符串值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引字符串值',
            },
        ),
        migrations.CreateModel(
            name='CICharValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='字符串值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '字符串值',
            },
        ),
    ]
