# Generated by Django 3.1.5 on 2021-02-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20210220_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemathroughfield',
            options={'verbose_name': '模型和字段穿梭表'},
        ),
        migrations.AlterField(
            model_name='schemathroughfield',
            name='field',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ci_schema', to='cmdb.cifield'),
        ),
        migrations.AlterField(
            model_name='schemathroughfield',
            name='schema',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ci_field', to='cmdb.cischema'),
        ),
    ]
