# Generated by Django 3.1.7 on 2021-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20210225_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cischema',
            name='alias',
            field=models.CharField(max_length=32, verbose_name='模型别名'),
        ),
        migrations.AlterField(
            model_name='cischema',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='cischema',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='图标'),
        ),
    ]
