# Generated by Django 3.1.7 on 2021-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20210302_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifield',
            name='value_type',
            field=models.CharField(choices=[('0', '整型'), ('1', '浮点型'), ('2', '文本型'), ('3', '日期时间'), ('4', '日期'), ('5', '时间'), ('6', 'JSON'), ('7', '字符串'), ('8', '枚举')], max_length=2, verbose_name='值的类型'),
        ),
    ]
