# Generated by Django 3.1.7 on 2021-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20210304_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cischema',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
