# Generated by Django 3.1.7 on 2021-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('user', models.CharField(max_length=64, verbose_name='操作者')),
                ('obj', models.TextField(blank=True, null=True, verbose_name='操作对象')),
                ('operate_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('change_message', models.TextField(blank=True, verbose_name='操作信息')),
            ],
            options={
                'verbose_name': '操作日志',
                'ordering': ['-id'],
            },
        ),
    ]
