# Generated by Django 3.1.7 on 2021-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='订阅名称')),
                ('subscriber', models.CharField(max_length=32, verbose_name='订阅者')),
                ('notify_url', models.CharField(max_length=255, verbose_name='通知url')),
                ('success_code', models.CharField(default='200', max_length=8, verbose_name='成功状态码')),
                ('timeout', models.CharField(default='60', max_length=8, verbose_name='超时时间')),
                ('meta', models.JSONField(verbose_name='订阅数据')),
            ],
        ),
    ]
