# Generated by Django 3.1.5 on 2021-02-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '配置项',
            },
        ),
        migrations.CreateModel(
            name='CIField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='字段名称')),
                ('alias', models.CharField(default='', max_length=32, verbose_name='字段别名')),
                ('value_type', models.CharField(choices=[('0', '整型'), ('1', '浮点型'), ('2', '文本型'), ('3', '日期时间'), ('4', '日期'), ('5', '时间'), ('6', 'JSON')], max_length=2, verbose_name='值的类型')),
                ('meta', models.JSONField(verbose_name='字段属性')),
            ],
            options={
                'verbose_name': '模型字段',
            },
        ),
        migrations.CreateModel(
            name='CISchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='模型名称')),
                ('alias', models.CharField(default='', max_length=32, verbose_name='模型别名')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('icon_url', models.CharField(default='', max_length=255, verbose_name='图标')),
            ],
            options={
                'verbose_name': '模型',
            },
        ),
        migrations.CreateModel(
            name='CITimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TimeField(verbose_name='时间值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '时间值',
            },
        ),
        migrations.CreateModel(
            name='CITextValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='文本型值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '文本型值',
            },
        ),
        migrations.CreateModel(
            name='CIJsonValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='JSON值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': 'JSON值',
            },
        ),
        migrations.CreateModel(
            name='CIIntValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='整型值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '整型值',
            },
        ),
        migrations.CreateModel(
            name='CIIndexTimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TimeField(db_index=True, verbose_name='索引时间值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引时间值',
            },
        ),
        migrations.CreateModel(
            name='CIIndexIntValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(db_index=True, verbose_name='索引整型值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引整型值',
            },
        ),
        migrations.CreateModel(
            name='CIIndexFloatValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(db_index=True, verbose_name='索引浮点型值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引浮点型值',
            },
        ),
        migrations.CreateModel(
            name='CIIndexDateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(db_index=True, verbose_name='索引日期值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引日期值',
            },
        ),
        migrations.CreateModel(
            name='CIIndexDatetimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(db_index=True, verbose_name='索引日期时间值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '索引日期时间值',
            },
        ),
        migrations.CreateModel(
            name='CIFloatValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='浮点型值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '浮点型值',
            },
        ),
        migrations.CreateModel(
            name='CIDateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(verbose_name='日期值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '日期值',
            },
        ),
        migrations.CreateModel(
            name='CIDatetimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(verbose_name='日期时间值')),
                ('ci', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ci')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.cifield')),
            ],
            options={
                'verbose_name': '日期时间值',
            },
        ),
        migrations.AddField(
            model_name='ci',
            name='schema',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cmdb.cischema'),
        ),
    ]
