# Generated by Django 3.1.5 on 2021-02-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifield',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='字段属性'),
        ),
    ]
