# Generated by Django 3.1.5 on 2021-02-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210220_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaThroughField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_schema', to='cmdb.cifield')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_field', to='cmdb.cischema')),
            ],
        ),
        migrations.AddField(
            model_name='cischema',
            name='field',
            field=models.ManyToManyField(related_name='schema', through='cmdb.SchemaThroughField', to='cmdb.CIField'),
        ),
    ]
