# Generated by Django 3.1.7 on 2021-02-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_relation_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CISchemaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='模型分组名称')),
                ('alias', models.CharField(default='', max_length=32, verbose_name='模型分组别名')),
            ],
            options={
                'verbose_name': '模型分组',
            },
        ),
        migrations.AddField(
            model_name='cischema',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='cmdb.cischemagroup'),
        ),
    ]
