# Generated by Django 3.1.7 on 2021-03-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20210301_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cischema',
            name='field',
        ),
        migrations.AddField(
            model_name='cifield',
            name='schema',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, related_name='field', to='cmdb.cischema'),
        ),
        migrations.DeleteModel(
            name='SchemaThroughField',
        ),
    ]
