# Generated by Django 3.1.7 on 2021-04-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_cischema_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIThroughRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='_parent', to='cmdb.ci')),
                ('parent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='_child', to='cmdb.ci')),
                ('schema_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='inst_relation', to='cmdb.schemathroughrelation')),
            ],
            options={
                'verbose_name': '实例和模型关系穿梭表',
            },
        ),
    ]
